version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: cosmos-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: cosmos-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - prometheus
    networks:
      - monitoring-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - monitoring-net
    # 注意：node-exporter 需要特殊权限来访问主机指标
    privileged: true
    pid: host

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring-net:
    driver: bridge