version: '3.1'

services:
  mongo:
    image: mongo:4.0.9
    command:
      - "--wiredTigerCacheSizeGB=10"
    restart: always
    volumes:
    - "./data/configdb:/data/configdb"
    - "./data/db:/data/db"
    ports:
    - 27017:27017
    #environment:
      #  MONGO_INITDB_ROOT_USERNAME: root
      #  MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8181:8081
    environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/