global:
  scrape_interval: 2s
  evaluation_interval: 2s

# 告警规则
rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "cosmos-node"
    static_configs:
      - targets: ["host.docker.internal:26660"] # 关键：使用 host.docker.internal 访问宿主机
        labels:
          instance: "cosmos-node"
          job: "cosmos"
  
  - job_name: 'cosmos-node-exporter'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:9500']

  - job_name: "loka-evm"
    static_configs:
      - targets: ["host.docker.internal:6065"] # 关键：使用 host.docker.internal 访问宿主机
        labels:
          instance: "loka-evm"
          job: "loka"

  - job_name: "node-exporter" # 系统指标
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          instance: "macos-host"

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:9323"] # Docker 指标端点
